### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by xstable** [cascremers/pdfdiff#3]
If I run pdfdiff, I got the following error: 

> File "./pdfdiff.py", line 144
>     print "Error: %s" % (notfound)
>                     ^
> SyntaxError: invalid syntax

- kdiff3 is installed, 
- xpdf is installed
- phyton is installed

uname -i :  4.9.61-3-MANJARO #1 SMP PREEMPT Thu Nov 9 01:18:52 UTC 2017 x86_64 GNU/Linux

**Comment by cascremers** [comment]
Currently, pdfdiff relies on Python 2. The error message suggest it is being run using Python 3.

This can be solved locally (by installing python 2 and using that to run `pdfdiff.py`), but ideally, we'd update pdfdiff to Python 3.

**Comment by maybe-hello-world** [comment]
@cascremers probably closed by #4 ?
