### ISSUE TITLE
not working on python3.9.1

### ISSUE THREAD

**Issue by dfrey** [cascremers/pdfdiff#5]
Hi cas, 
I just found this tool while reviewing a student's paper. 
I tested on my mac on python3 (v3.9.1) but I get the following error: 

Traceback (most recent call last):
  File "/usr/local/src/pdfdiff/pdfdiff.py", line 494, in <module>
    if len(filter(lambda s:s.startswith(diffViewerPrefix),get_viewer_list())) == 0:
TypeError: object of type 'filter' has no len()

The issue seems to be that filter returns something different than what it used to be. I will keep hunting for a fix, but if you have one I'd appreciate it, as I am not a python expert ;). 

BTW: I just looked at your webpage and I might contact you for work at some point ;)

**Comment by dfrey** [comment]
I found a "hack fix" 
if len(list(filter(lambda s:s.startswith(diffViewerPrefix),get_viewer_list()))) == 0:
by reading this https://portingguide.readthedocs.io/en/latest/iterators.html

I might send you a better version once I have read  about filter and map in python3

**Comment by dfrey** [comment]
Actually, if you want compatibility with Python2, I think the fix above is the best one, because in P3 filter returns an iterator, hence the problem.

**Comment by cascremers** [comment]
This should be fixed now with version 0.93. Thanks for reporting!
